# my global config
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'knetik-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s

    static_configs:
         - targets: ['prometheus:9090']


  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s

    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8484

    static_configs:
      - targets: ['cadvisor:8484']

  - job_name: 'prometheus-es-adapter'
    #scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-es-adapter:8080']

  #- job_name: 'elasticseach'
  #  # Override the global default and scrape targets from this job every 5 seconds.
  #  scrape_interval: 10s
  #  static_configs:
  #       - targets: ['elasticseach:9200']

  #- job_name: 'node-exporter'
  #  static_configs:
  #    - targets: ['node-exporter:9100']

#  - job_name: 'node-exporter'

    ## Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 5s

#    dns_sd_configs:
#    - names:
#      - 'tasks.node-exporter'
#      type: 'A'
#      port: 9100
    
##     static_configs:
##         - targets: ['node-exporter:9100']

# Remote write configuration.
remote_write:
  - url: http://prometheus-es-adapter:8080/write
    write_relabel_configs:
    - source_labels: [__name__]
      regex: container_memory_usage_bytes
      action: keep 
    - source_labels: [id]
      regex: /
      action: keep


# Remote read configuration
#remote_read:
#  - url: "http://prometheus-es-adapter:8080/read"
#  - basic_auth:
#    username: elastic
#    password: "MQMHUizRRXmJI12grG1e6g=="
#  - tls_config:
#    ca_file: "/usr/share/certs/ca/ca.crt"